name: R graph gallery
markdown: redcarpet
pygments: true
permalink: /:year/:month/:title/
url: http://maxpow3r.github.io/rgraphgallery
author:
    name: Hanna
    twitter: #
exclude:
    - LICENSE
    - README.md
    - CNAME
    - rgraphgallery.Rproj
    - /R
    - /R-plots
